global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'oracle-db'
    static_configs:
      - targets: ['oracledb-exporter:9161']

  - job_name: 'mysql-db'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'postgres-db'
    static_configs:
      - targets: ['postgres-exporter:9187']
